### ISSUE TITLE
Lantern stops proxying when starting to use the phone after being idle for long time but Lantern is still running

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern-mobile#36]
I saw this behavior whenever I let Lantern run for more than 2-3 hrs when the phone is not in use. When I start using my phone again, I have to go back to Lantern and flip the switch OFF and then ON. Only then it starts proxying.

**Comment by atavism** [comment]
@sunshine19090 Thanks. Do you know if you were disconnected from the Internet in the interim? The current behavior is for Lantern to turn itself off when it encounters a bunch of errors trying to proxy requests so that's possibly what happened. I added a connectivity checker so what we could do is just enter a suspended state if Lantern is left on with no Internet connection available and then just resume normal behavior once we re-connect.

**Comment by sunshine19090** [comment]
Makes sense @atavism. I will see if my internet connection goes off after a while when the phone is not in use. Will update it here.

**Comment by sunshine19090** [comment]
This is now fixed.
